### ISSUE TITLE
Trying download PSP covers - MemoryError

### ISSUE THREAD

**Issue by allexirlley** [Julioevm/tiny-scraper#3]
Hello! How are you?

Sorry for my English. I'm Brazilian.

I have an issue, when I try to download the cover art for some PSP games, tiny-scraper just closes unexpectedly. Looking at the log, the last line indicates that it's a MemoryError problem. See the log below:

> Starting Tiny Scraper...
Traceback (most recent call last):
  File "/mnt/sdcard/Roms/APPS/tiny_scraper/main.py", line 13, in <module>
    main()
  File "/mnt/sdcard/Roms/APPS/tiny_scraper/main.py", line 10, in main
    app.update()
  File "/mnt/sdcard/Roms/APPS/tiny_scraper/app.py", line 45, in update
    load_roms_menu()
  File "/mnt/sdcard/Roms/APPS/tiny_scraper/app.py", line 139, in load_roms_menu
    rom.set_crc(scraper.get_crc32_from_file(system_path / rom.filename))
  File "/mnt/sdcard/Roms/APPS/tiny_scraper/scraper.py", line 45, in get_crc32_from_file
    buf = rom.open(mode="rb").read()
MemoryError

[log.txt](https://github.com/user-attachments/files/18225214/log.txt)

**Comment by Julioevm** [comment]
Hi, thanks for reporting the issue.

A couple of questions:
What model do you have?
Does it happen when you try to download the media of a specific game? Can you tell me which one, and how big is the rom?
Does it happen when you're trying to scrape the whole system and its already scrapped a few roms?

My guess is that the psp rom files being larger than older consoles might be too much for the limited ram these systems have... since it reads the rom to generate a CRC code that is used by the media server to provide the correct files. Maybe theres an alternative to this...

**Comment by allexirlley** [comment]
Hello! Sorry for the delay.

The model I have is the Anbernic RG40XX H, and I'm trying to download some specific ROMs that have between 800mb and 1.7gb. I haven't scanned the entire system for a few reasons, such as RAM usage, battery saving and download time. I already have media for all the ROMs I have, basically, only some new PSP ROMs that have been causing this.

**Comment by allexirlley** [comment]
I just tested it and the problem was solved! 
Thank you very much for your attention.
